config/routes.rb
Rails.application.routes.draw do
  get "user/index"
  resources :posts
  resources :users, only: [:create]
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }

  # letter opener
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # mount LetterOpener::Engine, at: "/letter_opener" if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?



  # devise_for :users, controllers: { sessions: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest



  delete '/delete/user/:id', to: 'user#destroy', as: 'delete_user'
  root 'posts#index'

  # upload csv
  get '/upload/post', to: 'posts#upload_post', as: 'upload_post'
  post '/posts/upload_csv', to: 'posts#upload_csv'

  # download csv
  get '/posts/download/csv', to: 'posts#download_csv', as: 'download_posts_csv'

  #profile
  get '/user/profile', to: 'user#profile', as: 'user_profile'

  # edit profile back linkn

  get '/user/edit/profile', to: 'user#edit_profile', as: 'edit_profile'
  

  # change password
  get '/user/change/password', to: 'user#change_password', as: 'change_password'
  get '/password/change', to: 'password#edit', as: 'edit_password'
  patch '/password/change', to: 'password#update'


  # edit profile
  # patch '/profile/update', to: 'user#update', as: 'user_edit'
  resources :user do
    member do
      get 'edit'
      patch 'update'
    end
  end
 
  devise_scope :user do
    # post '/confirm/registration', to: 'registrations#confirm_registration', as: 'confirm_registration'
    get '/users/sign_up', to: 'devise/registrations#new', as: 'new_user_registraion'
    post '/user/create', to: 'registrations#create', as: 'user_create'
    post '/confirm_registration', to: 'registrations#confirm_registration', as: 'confirm_registration'
  end
  
end

app/models/user.rb
# require 'paperclip'
class User < ApplicationRecord
  extend Devise::Models
  has_attached_file :profile
  validates_attachment_content_type :profile, content_type: /\Aimage\/.*\z/
  has_many :posts, foreign_key: 'create_user_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  # for profile upload 
  mount_uploader :profile, ProfileUploader
  
  validates :name, presence: {message: "Name can't be blank."} 
  validates :email, presence: { message: "Email can't be blank." }
  validates :password, presence: { message: "Password can't be blank." }
  validates :password_confirmation, presence: { message: "Password confirmation can't be blank." }
  validates_confirmation_of :password, message: "Password and password confirmation do not match."
  validates :profile, presence: {message: "Profile can't be blank."}

  # email format
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "Invalid email format" }

  # enum utype: [:user, :moderator, :addevise :database_authenticatable, :registerable,
        

  # after_initialize :set_default_utype, :if => :new_record?
  # def set_default_utype
  #   self.utype ||= :user
  # end
  # enum utype: [:admin, :user]
  # after_initialize :set_default_role, :if => :new_record?
  # def set_default_role
  #   self.utype ||= :user
  # end


  def updating?
    self.persisted? && self.changed?
  end

 

  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :utype, :phone, :dob, :address, :profile)
  end

  def show
    render :new
  end
  
  def index
    if(current_user.utype == "0")
      @Users = User.page(params[:page]).per(5).order("id DESC")
      # if params[:name_keyword].present? || params[:email_keyword].present? || params[:from_keyword].present? || params[:to_keyword].present?
      #   # @Users = @Users.where("name LIKE ? OR email LIKE ?", "%#{params[:name_keyword]}%", "%#{params[:email_keyword]}%")
      #   # if params[:from_keyword].present? && params[:to_keyword].present?
      #   #   @Users = @Users.where("created_at BETWEEN ? AND ?", params[:from_keyword], params[:to_keyword])
      #   # end
      # end
      if params[:name_keyword].present?
        @Users = @Users.where("LOWER(name) LIKE ?", "%#{params[:name_keyword].downcase}%")
      end
      if params[:email_keyword].present?
        @Users = @Users.where("LOWER(email) LIKE ?", "%#{params[:email_keyword].downcase}%")
      end
      if params[:from_keyword].present? && params[:to_keyword].present?
        @Users = @Users.where("created_at BETWEEN ? AND ?", params[:from_keyword], params[:to_keyword])
      end
    else
      flash[:notice] = 'You do not have permission to access this page.'
      redirect_to root_path
    end
  end

  # for confirm
  def confirm
    @user = User.new(params[:post])
    render :confirm
  end

  # for delete
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to user_index_path, notice: "User  deleted successfully"
  end

  def edit
    @user = User.find(params[:id])
    render 'edit_profile'
  end

  def update
    @user = User.find(params[:id])
    if params[:commit] == "edit"
    has_errors = false

    if user_params["name"].empty?
      @user.errors.add(:name_error,"Name can't be blank.")
      has_errors = true
    end

    if user_params["email"].empty?
      @user.errors.add(:email_error, "Email can't be blank.")
      has_errors = true
    else
    unless valid_email_format?(user_params["email"])
      @user.errors.add(:email_error, "Email format is invalid.")
      has_errors = true
    end
    end
    if has_errors
      render :edit_profile and return
    end
      # for un choose image
      if user_params["profile"] == nil
        profile = @user.profile
      else
        profile = user_params["profile"]
      end

      # update process
      if  @user.update_attribute(:name, user_params["name"]) && 
          @user.update_attribute(:email, user_params["email"]) &&
          @user.update_attribute(:utype, user_params["utype"]) &&
          @user.update_attribute(:phone, user_params["phone"]) &&
          @user.update_attribute(:dob, user_params["dob"]) &&
          @user.update_attribute(:address, user_params["address"]) &&
          @user.update_attribute(:profile, profile) 

          # success condition
          redirect_to user_profile_path, notice: "User was successfully updated."
      else
          #fail condition
          render :edit_profile
      end

    elsif params[:commit] == "clear"
      # clear condition
      @user = User.new
      render :edit_profile

    end
  end

  def profile

  end

  def valid_email_format?(email)
    regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    regex.match?(email)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_delete_modal.html.erb
<!-- Modal for each user -->
<div class="modal fade" id="deleteModal<%= user.id %>" tabindex="-1" aria-labelledby="deleteModalLabel<%= user.id %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="detailModalLabel<%= user.id %>">Delete Confirm</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
       <div class="modal-body">
       <p class="text-danger">Are you sure to delete user?</p>
      <div class="container">
          <table class="table table-border-none">
            
              <tr>
                  <td><b>ID</b></td>
                  <td><%= user.id %></td>
              </tr>
              <tr>
                  <td><b>Name</b></td>
                  <td><%= user.name %></td>
              </tr>
              <tr>
                  <td><b>Type</b></td>
                  <td>
                      <% if user.utype == "0"%>
                        Admin
                      <%end%>
                      <% if user.utype == "1" %>
                        User
                      <%end%>
                  </td>
              </tr>
              <tr>
                  <td><b>Email</b></td>
                  <td><%= user.email %></td>
              </tr>
              <tr>
                  <td><b>Phone</b></td>
                  <td><%= user.phone %></td>
              </tr>
              <tr>
                  <td><b>Date of Birth</b></td>
                  <td><%= user.dob %></td>
              </tr>
              <tr>
                  <td><b>Address</b></td>
                  <td><%= user.address %></td>
              </tr>
          </table>
      </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= button_to "Delete", delete_user_path(user.id), method: :delete, class:"btn btn-danger"%>
    </div>
    </div>
  </div>
</div>

app/views/user/_detail_modal.html.erb
<div class="modal fade" id="detailModal<%= user.id %>" tabindex="-1" aria-labelledby="detailModalLabel<%= user.id %>" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="detailModalLabel<%= user.id %>">User  Detail</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
        <div class="container">
            <table class="table table-border-none">
            
                <tr>
                    <td rowspan="10">
                        <%= image_tag(user.profile.url, class: "profile-image") if user.profile.present? %>
                    </td>
                    <td><b>Name</b></td>
                    <td><%= user.name %></td>
                </tr>
                <tr>
                    <td><b>Type</b></td>
                    <td>
                        <% if user.utype == "0"%>
                        Admin
                        <%end%>
                        <% if user.utype == "1" %>
                        User
                        <%end%>
                    </td>
                </tr>
                <tr>
                    <td><b>Email</b></td>
                    <td><%= user.email %></td>
                </tr>
                <tr>
                    <td><b>Phone</b></td>
                    <td><%= user.phone %></td>
                </tr>
                <tr>
                    <td><b>Date of Birth</b></td>
                    <td><%= user.dob %></td>
                </tr>
                <tr>
                    <td><b>Address</b></td>
                    <td><%= user.address %></td>
                </tr>
                <tr>
                    <td><b>Created Date</b></td>
                    <td><%= user.created_at.strftime('%Y-%m-%d') %></td>
                </tr>
                <tr>
                    <td><b>Created User</b></td>
                    <td><%= user.name %></td>
                </tr>
                <tr>
                    <td><b>Updated Date</b></td>
                    <td><%= user.updated_at.strftime('%Y-%m-%d') %></td>
                </tr>
                <tr>
                    <td><b>Updated User</b></td>
                    <td><%= user.name %></td>
                </tr>
            </table>
        </div>
    </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
    </div>
    </div>
</div>

app/views/user/change_password.html.erb
<div class="w-50 m-auto p-2">
    <i class="fs-5 fa-solid fa-arrow-left"></i>
    <%= link_to "Back to Edit Profile", edit_profile_path %>
</div>
<div class="w-50 m-auto"><p class="text-danger"><%= notice %></p></div>
<div class="w-50 m-auto" style="border:1px solid green;padding:0px; padding-bottom:20px;border-radius:5px">
    <div class="bg-success p-2  text-light">Change Password</div>
    <%= form_with model: current_user , url: edit_password_path do |f| %>
        <table class="mt-3" style="width:100%">
            <tr>
              <td><div class="d-flex justify-content-end"><%= f.label :old_password , "Current Password"%><span class="text-danger">*</span></div></td>
              <td colspan="2"><%= f.password_field :old_password, class: "form-control my-2 w-75 m-auto", autofocus: true, autocomplete: "password" %>
               <div class="m-auto w-75">
                  <% if current_user.errors[:old_password].any? %>
                  <span class="text-danger" ><%= current_user.errors[:old_password].first %></span>
                  <% end %>
               </div>
               <div class="m-auto w-75">
                  <% if current_user.errors[:wrong].any? %>
                  <span class="text-danger" ><%= current_user.errors[:wrong].first %></span>
                  <% end %>
               </div>
              </td>
            </tr>
            <tr>
                <td><div class="d-flex justify-content-end"><%= f.label :new_password , "New Password"%><span class="text-danger">*</span></div></td>
                <td colspan="2"><%= f.password_field :new_password, class: "form-control my-2 w-75 m-auto", autofocus: true, autocomplete: "new_password" %>
                <div class="m-auto w-75">
                  <% if current_user.errors[:new_password].any? %>
                  <span class="text-danger" ><%= current_user.errors[:new_password].first %></span>
                  <% end %>
                </div>
                </td>
            </tr>
            <tr>
                <td><div class="d-flex justify-content-end"><%= f.label :new_password_confirmation , "New Confirm Password"%><span class="text-danger">*</span></div></td>
                <td colspan="2"><%= f.password_field :new_password_confirmation, class: "form-control my-2 w-75 m-auto", autofocus: true, autocomplete: "new_password_confirmation" %>
                <div class="m-auto w-75">
                  <% if current_user.errors[:new_password_confirmation].any? %>
                  <span class="text-danger" ><%= current_user.errors[:new_password_confirmation].first %></span>
                  <% end %>
                </div>
                <div class="m-auto w-75">
                  <% if current_user.errors[:notmatch].any? %>
                  <span class="text-danger" ><%= current_user.errors[:notmatch].first %></span>
                  <% end %>
                  </div>
                </td>
            </tr>
            <tr>
                <td><td>
                <td><div class="w-75 m-auto my-2"><%= f.submit "Update Password",class: "btn btn-sm btn-primary" %></div></td>
            </tr>
        </table>
  
        <% end %>
    
</div>

app/views/user/edit_profile.html.erb
<div class="w-50 m-auto p-2">
    <i class="fs-5 fa-solid fa-arrow-left"></i>
    <%= link_to "Back to Profile", user_profile_path %>
</div>
<div class="w-50 m-auto" style="border:1px solid green;padding:0px; padding-bottom:20px;border-radius:5px">
  <div class="bg-success p-2  text-light">Profile Edit</div>
  <%= form_with(model: @user, local: true) do |form| %>
  <table style="width:100%" class="mt-3">
    <tr>
        <td><div class="d-flex justify-content-end"><%= form.label :name ,"Name" %><span class="text-danger ms-2">*</span></div></td>
        <td><%= form.text_field :name,  class: "form-control my-1 m-auto w-75"  %>
             <div class="m-auto w-75">
                  <% if @user.errors[:name_error].any? %>
                  <span class="text-danger" ><%= @user.errors[:name_error].first %></span>
                  <% end %>
              </div>
        </td>
    </tr>
    <tr>
        <td><div class="d-flex justify-content-end"><%= form.label :email ,"Email" %><span class="text-danger ms-2">*</span></div></td>
        <td><%= form.text_field :email,  class: "form-control my-1 m-auto w-75"   %>
            <div class="m-auto w-75">
                <% if @user.errors[:email_error].any? %>
                <span class="text-danger" ><%= @user.errors[:email_error].first %></span>
                <% end %>
            </div>
        </td>
    </tr>
    <tr>
        <td><div class="d-flex justify-content-end"><%= form.label :utype ,"Type" %></div></td>
        <td> <%= form.select :utype, [["User ", 1], ["Admin", 0]], { include_blank: false }, { class: 'w-75 my-1 m-auto form-select' } %>
        </td>
    </tr>
    <tr>
      <td><div class="d-flex justify-content-end"><%= form.label :phone ,"Phone" %></div></td>
      <td><%= form.text_field :phone,  class: "form-control my-1 m-auto w-75" %></td>
    </tr>
    <tr>
      <td><div class="d-flex justify-content-end"><%= form.label :dob ,"Date of Birth" %></div></td>
      <td><%= form.date_field :dob,  class: "form-control my-1 m-auto w-75" %></td>
    </tr>
    <tr>
      <td><div class="d-flex justify-content-end"><%= form.label :address ,"Address" %></div></td>
      <td><%= form.text_field :address,  class: "form-control my-1 m-auto w-75" %></td>
    </tr>
    <tr>
      <td><div class="d-flex justify-content-end"><%= form.label :profile ,"Old Profile" %></div></td>
      <td> <div class="my-1 m-auto w-75"><%= image_tag(@user.profile.url, class: "main-profile-image") if @user.profile.present? %><div></td>
    </tr>
    <tr>
      <td><div class="d-flex justify-content-end"><%= form.label :profile ,"New Profile" %></div></td>
      <td><%= form.file_field :profile,  class: "form-control my-1 m-auto w-75" %></td>
    </tr>
    <tr>
      <td></td>
      <td>
          <div class="my-1 w-75 m-auto d-flex">
            <%= form.submit "Edit", name: "commit", value: "edit", class: "btn btn-primary"  %>
            <%= form.submit "Clear", name: "commit", value: "clear", class: "btn btn-secondary mx-1" %>
            <%= link_to "Change Password", change_password_path %>
          </div>
      </td>
    </tr>
   </table>
  <% end %>
</div>

app/views/user/index.html.erb
<header>
    <%= render "layouts/header"%>
<header>
<div class="container" style="width:90%">
  <p style="color: green"><%= notice %></p>
  <% content_for :title, "Users" %>
  <% if current_user %>
  <div class="bg-success p-2 text-light">User List</div>
      <div class="row justify-content-end my-3">
          <form>
             <div class="d-flex justify-content-between">
              <div class="w-100">
                <label>Name:</label>
                <input type="text" name="name_keyword",value="<%= params[:name_keyword] %>" >
              </div>

              <div class="w-100">
                <label>Email:</label>
                <input type="text" name="email_keyword",value="<%= params[:email_keyword] %>" >
              </div>
              
              <div  class="w-100">
                <label>From:</label>
                <input type="date" name="from_keyword",value="<%= params[:from_keyword] %>" >
              </div>

              <div class="w-100">
                <label>To:</label>
                <input type="date" name="to_keyword", value="<%= params[:to_keyword] %>" >
              </div>

              <div class="w-100">
                <button type="submit" class="btn btn-success m-2">Search</button>
              </div>
             </div>
          </form>

         
      </div>
      <table class="table table-striped">
            <tr>
                <th>No.</th>
                <th>Name</th>
                <th>Email</th>
                <th>Create User</th>
                <th>Phone</th>
                <th>Type</th>
                <th>Date of Birth</th>
                <th>Address</th>
                <th>Operation</th>
            </tr>
        <% @Users.each_with_index do |user , index|%>
            <tr>
                <td><%= index+1 %></td>
                <td><%= user.name%></td>
                <td><%= user.email%></td>
                <td><%= user.name%></td>       
                <td><%= user.phone%></td>
                <td>
                  <% if user.utype == "0"%>
                    Admin
                  <%end%>
                  <% if user.utype == "1" %>
                    User
                  <%end%>
                </td>
                <td><%= user.dob%></td>
                <td><%= user.address %></td>
                <td>
                <button type="button" class="btn btn-sm btn-secondary" data-bs-toggle="modal" data-bs-target="#detailModal<%= user.id %>">
                Detail
                </button>
                <%= render partial: 'detail_modal', locals: { user: user } %>


                <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal<%= user.id %>">
                Delete
                </button>
                <%= render partial: 'delete_modal', locals: { user: user } %>
                </td>
            </tr>
      <% end %>
    </table>
        <div class="d-flex justify-content-end">
                <%= paginate @Users %>
        </div>
    </div>
    <% end %>
</div>
<%= render "layouts/footer"%>

app/views/user/profile.html.erb
<div class="w-50 m-auto p-2">
    <i class="fs-5 fa-solid fa-arrow-left"></i>
    <%= link_to "Back", posts_path %>
    <p style="color: green"><%= notice %></p>

</div>
<div class="w-50 m-auto" style="border:1px solid green;padding:0px; padding-bottom:20px;border-radius:5px">
      <div class="bg-success p-2  text-light">Profile</div>
      <table class="table table-border-none">
                              <tr>
                                  <td rowspan="10" class=" w-25">
                                      <%= image_tag(@user.profile.url, class: "main-profile-image") if @user.profile.present? %>
                                  </td>
                                  <td><b>Name</b></td>
                                  <td><%= @user.name %></td>
                              </tr>
                              <tr>
                                  <td><b>Type</b></td>
                                  <td>
                                      <% if @user.utype == "0"%>
                                        Admin
                                      <%end%>
                                      <% if @user.utype == "1" %>
                                        User
                                      <%end%>
                                  </td>
                              </tr>
                              <tr>
                                  <td><b>Email</b></td>
                                  <td><%= @user.email %></td>
                              </tr>
                              <tr>
                                  <td><b>Phone</b></td>
                                  <td><%= @user.phone %></td>
                              </tr>
                              <tr>
                                  <td><b>Date of Birth</b></td>
                                  <td><%= @user.dob %></td>
                              </tr>
                              <tr>
                                  <td><b>Address</b></td>
                                  <td><%= @user.address %></td>
                              </tr>
                              <tr>
                                  <td><%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %></td>
                                  <td></td>
                              <tr>
                          </table>   
</div>
<%= render "layouts/footer"%>