config/routes.rb
Rails.application.routes.draw do
  get "user/index"
  resources :posts
  resources :users, only: [:create]
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }

  # letter opener
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # mount LetterOpener::Engine, at: "/letter_opener" if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?



  # devise_for :users, controllers: { sessions: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest



  delete '/delete/user/:id', to: 'user#destroy', as: 'delete_user'
  root 'posts#index'

  # upload csv
  get '/upload/post', to: 'posts#upload_post', as: 'upload_post'
  post '/posts/upload_csv', to: 'posts#upload_csv'

  # download csv
  get '/posts/download/csv', to: 'posts#download_csv', as: 'download_posts_csv'

  #profile
  get '/user/profile', to: 'user#profile', as: 'user_profile'

  # edit profile back linkn

  get '/user/edit/profile', to: 'user#edit_profile', as: 'edit_profile'
  

  # change password
  get '/user/change/password', to: 'user#change_password', as: 'change_password'
  get '/password/change', to: 'password#edit', as: 'edit_password'
  patch '/password/change', to: 'password#update'


  # edit profile
  # patch '/profile/update', to: 'user#update', as: 'user_edit'
  resources :user do
    member do
      get 'edit'
      patch 'update'
    end
  end
 
  devise_scope :user do
    # post '/confirm/registration', to: 'registrations#confirm_registration', as: 'confirm_registration'
    get '/users/sign_up', to: 'devise/registrations#new', as: 'new_user_registraion'
    post '/user/create', to: 'registrations#create', as: 'user_create'
    post '/confirm_registration', to: 'registrations#confirm_registration', as: 'confirm_registration'
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: {message: "Title can't be blank."},
                      length: { maximum: 255, message: "255 characters is the maximum allowed."}
    validates :description, presence: {message: "Description can't be blank."}   
    belongs_to :user, foreign_key: :create_user_id
end

app/controllers/posts_controller.rb
require 'csv'
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token #csrf token
  before_action :authenticate_user!
  # GET /posts or /posts.json
  def index
    @posts = Post.all
        if current_user.utype == "1"
          @posts = Post.includes(:user).where(create_user_id: current_user.id).page(params[:page]).per(4).order("id DESC")
         
        else
          @posts = Post.includes(:user).page(params[:page]).per(4).order("id DESC")
        end

        # for search with keyword
        if params[:keyword].present?
          @posts = @posts.where("title LIKE ? OR description LIKE ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%")
        end
          @posts = @posts.page(params[:page]).per(4).order("id DESC")
  end


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end
 
  # for confirm
  def confirm
    @post = Post.new(params[:post])
    render :confirm
  end

  def upload_csv
    csv_file = params['csv_file']
    if csv_file.present?
      detected_encoding = CharDet.detect(File.read(csv_file.path))[:encoding]
      csv_content = File.read(csv_file.path).encode('UTF-8', detected_encoding, invalid: :replace, undef: :replace, replace: '')
  
      # file type validation
      if !csv_file.content_type.match?(/text\/csv/)
        @error = 'Please choose a CSV file'
        return render :upload_post
      end
  
      # parse CSV file
      csv = CSV.parse(csv_content, headers: true)
  
      # check number of columns in the first row
      if csv.first.size != 3
        @error = 'Post upload csv must have 3 columns'
        return render :upload_post
      else
        # process CSV data
        csv.each do |row|
          @post = Post.new
          @post.title = row['Title']
          @post.description = row['Description']
          @post.status = row['Status']
          @post.create_user_id = current_user.id
          @post.updated_user_id = current_user.id
          @post.created_at = Time.current
          @post.updated_at = Time.current
          begin
            @post.save!
          rescue ActiveRecord::RecordInvalid => e
            Rails.logger.error "Error saving post: #{e.message}"
            flash[:error] = "Error saving post: #{e.message}"
            render :index and return
          end
        end
        flash[:notice] = 'CSV file uploaded successfully!'
        redirect_to root_path
      end
    else
      @error = "Please choose a file"
      return render :upload_post
    end
  end

  def download_csv
    request.format = :csv
    @posts = Post.all
    csv_string = CSV.generate do |csv|
      csv << ['id', 'title', 'description', 'status', 'create_user_id', 'updated_user_id','deleted_user_id','deleted_at','created_at','updated_at']
      @posts.each do |post|
        csv << [
          post.id,
          post.title,
          post.description,
          post.status,
          post.create_user_id,
          post.updated_user_id,
          post.deleted_user_id,
          post.deleted_at,
          post.created_at.strftime('%Y/%m/%d'),
          post.updated_at.strftime('%Y/%m/%d')
        ]
      end
    end

    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"posts_#{Time.current.strftime('%Y%m%d%H%M%S')}.csv\""
        headers['Content-Type'] = 'text/csv'
        send_data csv_string, type: 'text/csv', disposition: 'attachment'
      end
    end

  end


  def create
    if params[:commit] == "create"
      @post = Post.new(post_params)
      if @post.valid?
        session[:post] = @post
        render :new_post_confirm
      else
        render :new
      end
    elsif params[:commit] == "clear"
      # session[:post] = nil
      @post = Post.new
      render :new
    elsif params[:commit] == "cancel"
      # session[:post] = nil
      redirect_to posts_path
    elsif params[:commit] == "confirm"
      post_attributes = session[:post]
      @post = Post.new(post_attributes)
      if @post.save
        session[:post] = nil
        redirect_to posts_path, notice: "Post was successfully created."
      else
      end
    end

 
    
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update_post
   
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update 
    @post = Post.find(params[:id])
      # for edit button 
      if params[:commit] == "edit"
        @post.assign_attributes(post_params)
        if post_params[:title].empty?
          @post.errors.add(:title, "Titel can't be blank")
        end
        if @post.valid?
          render :edit_post_confirm
        else
          render :edit
        end
      end 
      if params[:commit] == "clear"
        @post.assign_attributes({ title: "", description: "" })
        render :edit
      end
      if params[:commit] == "confirm"
        if @post.update(post_params)
          redirect_to posts_path, notice: "Post was successfully updated."
        end
      end
      if params[:commit] == "cancle"
          redirect_to edit_post_path
      end
   end
  

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :status, :create_user_id, :updated_user_id)
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_buttons.erb
<div>
    <%= form.submit "Create", name: "commit", value: "create" %>
    <%= form.submit "Clear", name: "commit", value: "clear" %>
</div>

app/views/posts/_delete_modal.html.erb
<div class="modal fade" id="deleteModal<%= post.id %>" tabindex="-1" aria-labelledby="deleteModalLabel<%= post.id %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="deleteModalLabel<%= post.id %>">Delete Confirm</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <p class="text-danger">Are you sure to delete post?</p>
      <div class="container">
          <table class="table table-border-none">
              <tr>
                  <td><b>Title</b></td>
                  <td> <%= post.title %></td>
              </tr>
              <tr>
                  <td><b>Description</b></td>
                  <td> <%= post.description %></td>
              </tr>
              <tr>
                  <td><b>Status</b></td>
                  <td> 
                      <%if post.status == 1 %>
                        Active
                      <% else %>
                        Inactive
                      <% end %>
                  </td>
              </tr>
              <tr>
                  <td><b>Created Date</b></td>
                  <td> <%= post.created_at.strftime('%Y-%m-%d') %></td>
              </tr>
              <tr>
                  <td><b>Updated Date</b></td>
                  <td> <%= post.updated_at.strftime('%Y-%m-%d') %></td>
              </tr>
          </table>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      <%= button_to "Delete", post, method: :delete ,class:"btn btn-danger" %> 
    </div>
  </div>
</div>
</div>

app/views/posts/_detail_modal.html.erb
<div class="modal fade" id="detailModal<%= post.id %>" tabindex="-1" aria-labelledby="detailModalLabel<%= post.id %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="detailModalLabel<%= post.id %>">Post  Detail</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="container">
          <table class="table table-border-none">
            <tr>
              <td><b>Title</b></td>
              <td> <%= post.title %></td>
            </tr>
            <tr>
              <td><b>Description</b></td>
              <td> <%= post.description %></td>
            </tr>
            <tr>
              <td><b>Status</b></td>
              <td> 
                <% if post.status == 1 %>
                  Active
                <% end %>
                <% if post.status == 0 %>
                  Inactive
                <% end %>
              </td>
            </tr>
            <tr>
              <td><b>Created Date</b></td>
              <td> 
                <%= post.created_at.strftime("%Y-%m-%d") %>
              </td>
            </tr>
            <tr>
              <td><b>Created User</b></td>
              <td> 
                <%= current_user.name%>
              </td>
            </tr>
            <tr>
              <td><b>Updated User</b></td>
              <td> 
                <%= current_user.name%>
              </td>
          </tr>
          </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> &nbsp;&nbsp;
      </div>
    </div>
  </div>
</div>

app/views/posts/_edit_form.html.erb
<% @create_user_id = current_user.id %>
<% @updated_user_id = current_user.id %>
<%= form_with(model: post) do |form| %>
<table class="mt-5 m-auto" style="width:50%">
  <tr>
    <td><%= form.label :title%></td>
    <td>
      <%= form.text_field :title,class: "form-control my-2" %>
      <% if post.errors[:title].any? %>
        <span class="text-danger"><%= post.errors[:title].first %></span>
      <% end %>
    </td>
    <td</td>
  </tr>

  <tr>
    <td><%= form.label :Description%></td>
    <td>
      <%= form.text_area :description, class: "form-control my-2"%>
      <% if post.errors[:description].any? %>
        <span class="text-danger"><%= post.errors[:description].first %></span>
      <% end %>
    </td>
  </tr>
    <%= form.hidden_field :status %>
    <%= form.hidden_field :create_user_id ,value: @create_user_id %>
    <%= form.hidden_field :updated_user_id,value: @updated_user_id %>
  <tr>
    <td>Status</td>
    <td>
      <%= hidden_field_tag "post[status]", 0 %>
      <%= check_box_tag "post[status]", 1, @post.status == 1, class: "my-2" %>
    </td>
  </tr>
  <tr>
      <td></td>
      <td>
        <%= form.submit "Edit", name: "commit", value: "edit" %>
        <%= form.submit "Clear", name: "commit", value: "clear" %>
      </td>
  </tr>
  </table>
<% end %>

app/views/posts/_form.html.erb
<% @create_user_id = current_user.id %>
<% @updated_user_id = current_user.id %>

<%= form_with(model: post) do |form| %>
<table class="mt-5 m-auto" style="width:50%">
  <tr>
    <td><%= form.label :title%></td>
    <td>
      <%= form.text_field :title,class: "form-control my-2" %>
      <% if post.errors[:title].any? %>
        <span class="text-danger"><%= post.errors[:title].first %></span>
      <% end %>
    </td>
    <td</td>
  </tr>

  <tr>
    <td><%= form.label :Description%></td>
    <td>
      <%= form.text_area :description, class: "form-control my-2"%>
      <% if post.errors[:description].any? %>
        <span class="text-danger"><%= post.errors[:description].first %></span>
      <% end %>
    </td>
  </tr>
    <%= form.hidden_field :status %>
    <%= form.hidden_field :create_user_id ,value: @create_user_id %>
    <%= form.hidden_field :updated_user_id,value: @updated_user_id %>
  <tr>
      <td></td>
      <td>
        <%= form.submit "Create", name: "commit", value: "create" %>
        <%= form.submit "Clear", name: "commit", value: "clear" %>
      </td>
  </tr>
  </table>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

</div>

app/views/posts/edit.html.erb
<header>
    <%= render "layouts/header"%>
 <header>
<div class="container">
  <% content_for :title, "Posts" %>
  <div class="p-2">
    <i class="fs-5 fa-solid fa-arrow-left"></i>
    <%= link_to "Back", posts_path %>
  </div>
  <% if current_user %>
    <div class="bg-success mt-2 p-2 text-light">Edit Post</div>
    <%= render "edit_form", post: @post %>
    <br>
  <% end %>
</div>
<%= render "layouts/footer"%>

app/views/posts/edit_post_confirm.html.erb
<header>
    <%= render "layouts/header"%>
 <header>
<div class="container">
  <% content_for :title, "Posts" %>
  <% if current_user %>
    <div class="bg-success mt-2 p-2 text-light">Edit Post</div>
    <%= form_with(model: @post) do |form| %>
      <table class="mt-5 m-auto" style="width:50%">
        <tr>
          <td><%= form.label :title, style: "display: block" %></td>
          <td>
              <%= form.text_field :title,class: "form-control my-2" %>
          </td>
        </tr>
        <tr>
          <td><%= form.label :description, style: "display: block" %></td>
          <td>
              <%= form.text_area :description,class: "form-control my-2" %>
          </td>
        </tr>
        <tr>
            <td>Status</td>
            <td>
              <%= hidden_field_tag "post[status]", 0 %>
              <%= check_box_tag "post[status]", 1, @post.status == 1, class: "my-2" %>
            </td>
        </tr>
        <tr>
          <td></td>
          <td>
              <%= form.submit "Confirm",class: "btn btn-sm btn-primary", name: "commit", value: "confirm" %>
              <%= form.submit "Cancle",class: "btn btn-sm btn-secondary", name: "commit", value: "cancle" %>
          </td>
        </tr>
      <table>
    <% end %>
    <% end %>
</div>
<%= render "layouts/footer"%>

app/views/posts/index.html.erb
<header>
    <%= render "layouts/header"%>
<header>
<div class="container">
  <p style="color: green"><%= notice %></p>
  <% content_for :title, "Posts" %>
  <% if current_user %>
    <div class="bg-success p-2 text-light">Posts List</div>
      <div class="row justify-content-end mt-2">
          <form>
              <label>Keyword : </label>
              <input type="text" name="keyword">
              <button type="submit" class="btn btn-light">Search</button>
          </form>
          <%= link_to "Create", new_post_path, class:"col-1 mx-1 text-light p-2 bg-success rounded text-decoration-none"%> &nbsp;&nbsp;
          <%= link_to "Upload", upload_post_path, class:"col-1 mx-1 text-light p-2 bg-success rounded text-decoration-none"%> &nbsp;&nbsp;
          <%= link_to "Download", download_posts_csv_path, class:"col-1 mx-1 text-light p-2 bg-success rounded text-decoration-none"%>
      </div>
      <div id="posts">
        <table class='table table-striped'>
          <thead>
            <tr>
              <th>No.</th>
              <th>Post Title</th>
              <th>Post Description</th>
              <th>Posted User</th>
              <th>Posted Date</th>
              <th>Operation</th>
            </tr>
          </thead>
          <% if @posts.any?  %>
            <% @posts.each_with_index do |post, index| %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= post.title %></td>
                <td><%= post.description %></td>
                <td><%= post.user.name%></td>
                <td><%= post.created_at.strftime("%Y-%m-%d")%></td>
                <td>
                  <div class="d-flex">
                    <%= link_to "Edit", edit_post_path(post),class:"btn btn-info" %> &nbsp;&nbsp;
                    <button type="button" class="btn btn-sm btn-secondary" data-bs-toggle="modal" data-bs-target="#detailModal<%= post.id %>">
                    Detail 
                    </button>&nbsp;&nbsp;
                    <%= render partial: 'detail_modal', locals: { post: post } %>
                     <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal<%= post.id %>">
                    Delete 
                    </button>&nbsp;&nbsp;
                    <%= render partial: 'delete_modal', locals: { post: post } %>
                </td>
              </tr>
            <% end %>
            <% else %>
              <tr>
                 <td colspan="7"><center>No data available in table</center></td>
              </tr>
            <% end %>
          </table>
          <div class="d-flex justify-content-end">
              <%= paginate @posts %>
          </div>
        
      </div>
  <% end %>
</div>
<%= render "layouts/footer"%>

app/views/posts/new.html.erb
<header>
    <%= render "layouts/header"%>
</header>
<div class="container">
  <% content_for :title, "New post" %>
  <div class="p-2">
    <i class="fs-5 fa-solid fa-arrow-left"></i>
    <%= link_to "Back", posts_path %>
  </div>
  <% if current_user %>
    <div class="bg-success p-2 text-light">Create Post</div>
    <%= render "form", post: @post %>
    <br>
  <% end %>
</div>
<%= render "layouts/footer"%>

app/views/posts/new_post_confirm.html.erb
<header>
    <%= render "layouts/header"%>
 <header>
<div class="container">
  <% content_for :title, "Posts" %>
  <% if current_user %>
    <div class="bg-success mt-2 p-2 text-light">Edit Post</div>
    <%= form_with(model: @post) do |form| %>
      <table class="mt-5 m-auto" style="width:50%">
        <tr>
          <td><%= form.label :title, style: "display: block" %></td>
          <td>
              <%= form.text_field :title,class: "form-control my-2" , disabled: true%>
          </td>
        </tr>
        <tr>
          <td><%= form.label :description, style: "display: block" %></td>
          <td>
              <%= form.text_area :description,class: "form-control my-2", disabled: true %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
              <%= form.submit "Confirm",class: "btn btn-sm btn-primary", name: "commit", value: "confirm" %>
              <%= form.submit "Cancle",class: "btn btn-sm btn-secondary", name: "commit", value: "cancle" %>
          </td>
        </tr>
      <table>
    <% end %>
    <% end %>
</div>
<%= render "layouts/footer"%>

app/views/posts/show.html.erb
<header>
    <%= render "layouts/header"%>
  <header>
<p style="color: green"><%= notice %></p>
<%= render @post %>
<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/posts/upload_post.html.erb
<header>
    <%= render "layouts/header"%>
<header>
<div class="container">
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= @error %></p>
  <% content_for :title, "Posts" %>
  <% if current_user %>
    <div class="bg-success p-2 text-light">Upload Post</div>
      <div class="row justify-content-end mt-2">
        <form enctype="multipart/form-data" action="/posts/upload_csv" method="post">
            <table class="d-flex justify-content-center">
               <tr>
                    <td> <label class="">CSV File</label></td>
                    <td><input type="file" class=" form-control my-2" name="csv_file"></td>
               </tr>
               <tr>
                    <td>
                    </td>
                    <td>
                      <%= submit_tag "Upload", class: "btn btn-sm btn-success" %>
                      <input type="reset" value="Clear" class="btn btn-sm btn-success">
                    </td>
               </tr>
            </table>
        </form>
        </div>
    </div>
  <% end %>
</div>
<%= render "layouts/footer"%>