config/routes.rb
Rails.application.routes.draw do
  get "user/index"
  resources :posts
  resources :users, only: [:create]
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }

  # letter opener
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # mount LetterOpener::Engine, at: "/letter_opener" if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?



  # devise_for :users, controllers: { sessions: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest



  delete '/delete/user/:id', to: 'user#destroy', as: 'delete_user'
  root 'posts#index'

  # upload csv
  get '/upload/post', to: 'posts#upload_post', as: 'upload_post'
  post '/posts/upload_csv', to: 'posts#upload_csv'

  # download csv
  get '/posts/download/csv', to: 'posts#download_csv', as: 'download_posts_csv'

  #profile
  get '/user/profile', to: 'user#profile', as: 'user_profile'

  # edit profile back linkn

  get '/user/edit/profile', to: 'user#edit_profile', as: 'edit_profile'
  

  # change password
  get '/user/change/password', to: 'user#change_password', as: 'change_password'
  get '/password/change', to: 'password#edit', as: 'edit_password'
  patch '/password/change', to: 'password#update'


  # edit profile
  # patch '/profile/update', to: 'user#update', as: 'user_edit'
  resources :user do
    member do
      get 'edit'
      patch 'update'
    end
  end
 
  devise_scope :user do
    # post '/confirm/registration', to: 'registrations#confirm_registration', as: 'confirm_registration'
    get '/users/sign_up', to: 'devise/registrations#new', as: 'new_user_registraion'
    post '/user/create', to: 'registrations#create', as: 'user_create'
    post '/confirm_registration', to: 'registrations#confirm_registration', as: 'confirm_registration'
  end
  
end

app/views/layouts/_footer.erb
  <footer class="bg-light d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">Seattle consulting Myanmar</span>
    </div>
    <div class="col-md-5 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="50" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="mb-3 mb-md-0 text-muted">Copyright © Seattle Consulting 
        Myanmar Co., Ltd. All rights reserved.</span>
    </div>
  </footer>

app/views/layouts/_header.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Bulletin_Board", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
           <%= link_to "Users", user_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "Posts", posts_path,  class: "nav-link"  %>
        </li>
      </ul>  
    </div>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <div class="dropdown">
      <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.name%>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li class="nav-item">
          <%= link_to  "Profile" , user_profile_path,  class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= button_to "Log Out", destroy_user_session_path, class: "nav-link btn btn-sm", :method => 'delete', data:{turbo: "false"} %>
        </li>
          </ul>
        </div>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title><%= content_for(:title) || "Bltsec" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>


    


    <style>
      footer{
        position:absolute;
        bottom:-30px !important;
        width:100%;
      }
      .profile-image{
        width: 100px;
        height: 100px;
        border: 1px solid black;
      }
      .main-profile-image{
        width: 150px;
        height: 150px;
        border: 1px solid black;
        margin:10px;
      }

    </style>
  </head>

  <body>
    <%= yield %>
  </body>
    
 
</html>